### ISSUE TITLE
@angular/flex-layout column is not responding using percentage % 

### ISSUE THREAD

**Issue by paco76** [angular/flex-layout#1048]
# Bug Report

#### What is the expected behavior?
the inner div to take 50% of the page when applying fxFlex="50%"

#### What is the current behavior?
it is only taking the height of the inner text 

#### What are the steps to reproduce?
here is a StackBlitz
https://stackblitz.com/edit/angular-qtr5hm?embed=1&file=src/app/app.component.html

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  }

Ubuntu 18.04.2 LTS
Chromium Version 73.0.3683.86 (Official Build) snap (64-bit)

#### Is there anything else we should know?
please help me understand why?

**Comment by mainawycliffe** [comment]
This is a CSS thing, am not the best person to explain this but i will try. For a child to be % height of the parent, the height needs to have a height in the first place. From you example, if you set the height of the parent, then the height of the parent, the child with the percentage height will expand to occupy 50%, while the other two will divide the remaining height equally.

This is why when you set the height using viewPort height (vh), it works since you are setting the height of the child relative to the viewport height and not parent. The parent will grow to accomodate the new height.

**Comment by paco76** [comment]
Hi mainamycliffe
still not working even when you set the parent div to be 100%.
it worked before though.. any other suggestions??

**Comment by mainawycliffe** [comment]
Can you try and set the height of the parent in Pixels or Vh, not 100%, even it faces the same problem as its child since its a child of body, i know this works as i tested it in your demo yesterday.

**Comment by paco76** [comment]
thank you mainamycliffe, it works!
still I wonder why do I have to use vh or px? what's wrong with using % ??
as I understand best practice is to set the main page of the app to 
html, body {
    height: 100%;
    ...
}

**Comment by CaerusKaru** [comment]
Thank you @mainawycliffe! Closing this as resolved.
