### ISSUE TITLE
Both sm and xs breakpoints are active when screen width is 600px

### ISSUE THREAD

**Issue by k-schneider** [angular/flex-layout#1052]
# Bug Report

#### What is the expected behavior?

I believe xs is supposed to kick in at 599px so I'd expect that only sm would be active at this point.

#### What is the current behavior?

Both sm and xs are active.

#### What are the steps to reproduce?

```
<div fxHide fxShow.gt-xs>fxHide fxShow.gt-xs</div>
<div fxHide fxShow.sm>fxHide fxShow.sm</div>
<div fxHide fxShow.xs>fxHide fxShow.xs</div>
```

When viewport width is exactly 600px all of these elements will display.

Example here:
https://stackblitz.com/edit/angular-flex-layout-seed-aojwqc

#### What is the use-case or motivation for changing an existing behavior?

Having both breakpoints active can lead to unexpected renders.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

All as far as I know.

#### Is there anything else we should know?

Nope.

**Comment by CaerusKaru** [comment]
This is very interesting. I wonder if it has anything to do with #1004. We'll investigate further, but this is definitely a weird one.

**Comment by dpereira411** [comment]
I'm having a similar problem. When using `fxHide.gt-sm="true"` and `fxHide.lt-md=”true”` at two `div`s, both are hidden at 960px.

**Comment by k0hamed** [comment]
@CaerusKaru as you mentioned this issue is caused by #1004 ( updated by #1006 ). It's a weird behavior in chrome (firefox isn't affected) that treats .99 as 1 so 599.99 is 600 (599.98 is fine though [as shown here](https://codepen.io/k0hamed/pen/yWRJxm) ) 

I don't know if it's a bug in chrome or browsers are free in treating fractions as in the [W3 specifications](https://www.w3.org/TR/mediaqueries-4/#mq-min-max) it's mentioned that for sub-pixels or fractions it's preferred to use [range context](https://www.w3.org/TR/mediaqueries-4/#range-context). 

So lowering the breakpoints to .98 or .9 would be a fix.

**Comment by CaerusKaru** [comment]
@k0hamed Are you interested in submitting a PR for this? Otherwise I'll patch it in the coming weeks.

**Comment by k0hamed** [comment]
@CaerusKaru No problem, I'll submit a PR with this fix.
