### ISSUE TITLE
element.style is undefined

### ISSUE THREAD

**Issue by alessiostalla** [angular/flex-layout#1058]
# Bug Report

```
<div fxFlexFill fxLayout="column" fxLayoutAlign="space-between">
  <ng-template fxFlex="none" my-directive></ng-template>
  Content
</div>
```

**ERROR TypeError: "element.style is undefined".** The fxFlex directive tries to apply a style to a node which is a comment.

#### What is the expected behavior?

No error is thrown.

#### What is the current behavior?

An error is thrown.

#### What are the steps to reproduce?

[StackBlitz example](https://stackblitz.com/edit/angular-flex-layout-seed-qkprfy?file=app%2Fapp.component.ts)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 7.2.14 Material 7.3.7
The exact error reported comes from Firefox. Chrome fails with a different error message, but the cause is the same.

#### Is there anything else we should know?

Wrapping the template with a div and placing the `fxFlex="none"` directive on it fixes the issue.

**Comment by Splaktar** [comment]
You can't put directives, random attributes, or classes on your `ng-template`s. This is because [they are not associated with DOM elements](https://angular.io/guide/structural-directives#the-ng-template) directly. This is why you need to wrap the `ng-template` or put an element in the `ng-template` for styling or layout.

You can pass Template Input Variables into an `ng-template` via the [microsyntax](https://angular.io/guide/structural-directives#microsyntax) described in the docs.

**Comment by CaerusKaru** [comment]
Thanks @Splaktar. I'm closing this issue as it's not an issue with Flex Layout.
