### ISSUE TITLE
fxLayoutGap for column disappears on resize

### ISSUE THREAD

**Issue by blogcraft** [angular/flex-layout#1097]
# Bug Report

#### What is the expected behavior?

I have a general column that has several rows with gaps and rows.
I expect the gap between these rows to remain despite the screen size change

#### What is the current behavior?

Start the app from StackBlitz (link below). App must start with a wide browser to see the behaviour.

1. The margin Bottom of each row is duplicated. (error)

2. Then the screen is rezised to a smaller version, the screen adapts (correct)

3. Returning the screen to the initial width eliminates the margin bottom in the row (error)

#### What are the steps to reproduce?
*  [StackBlitz](https://stackblitz.com/edit/angular-flex-layout-seed-psg7uh) 

#### What is the use-case or motivation for changing an existing behavior?
The grid is unreliable

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 8.1.1
Material 8.1.1
Typescript 3.4.5

**Comment by blogcraft** [comment]
any feedback?

**Comment by blogcraft** [comment]
@CaerusKaru am I doing something wrong? Or there is a problem with fxLayoutGap?

**Comment by blogcraft** [comment]
😡

**Comment by blogcraft** [comment]
Thankyou Angular Team for taking the time to delete a comment and still continue to ignore the issue (3 months and not a single comment yet).

**Comment by CaerusKaru** [comment]
The issue here is a little annoying, unfortunately. You have a nested `fxLayoutGap` inside another `fxLayoutGap`. The parent on reflow is clearing the margin (needed for grid mode) of its only descendant child (the one hosting the grid gap directive).

The solution for this is a new style reconciliation algorithm that we're writing, but the workaround is to simply remove the parent `fxLayoutGap` and add the margin styles you want manually (since it's not grid mode it should be relatively straightforward, and may not be needed at all).

I'm closing this and opening an issue for the reconciliation rewrite, and I hope this workaround is sufficient for you.
