### ISSUE TITLE
Compile --aot error

### ISSUE THREAD

**Issue by GlauberF** [angular/flex-layout#1101]
![Captura de Tela_selecionar área_20190723150659](https://user-images.githubusercontent.com/11314585/61736001-86ff0580-ad5b-11e9-82f7-b4ac70ab66a0.png)

![Captura de Tela_selecionar área_20190723150432](https://user-images.githubusercontent.com/11314585/61735960-73ec3580-ad5b-11e9-92bf-259eaffd3743.png)

**Comment by CaerusKaru** [comment]
I'm assuming these are images, since it's showing up as blank on my screen. I'm going to close this issue. Please open a new one following the issue template, using words instead of pictures for those of us who can't view them. Also note that issues with `ngcc` should be filed under the angular/angular repository.
