### ISSUE TITLE
Flex Layout CSS not applied to component divs when imported via module

### ISSUE THREAD

**Issue by ebussa** [angular/flex-layout#1136]
# Bug Report

#### What is the expected behavior?
Two identical flex divs should be displayed in the same order.

#### What is the current behavior?
Two identical flex divs are displayed in differing order.

#### What are the steps to reproduce?
Create a layout container with flex divs that appear in a modified order.  Now create that some set of divs in a component and import that component into the app.component via a module.

*  StackBlitz starter: 
https://stackblitz.com/edit/responsive-menu-angular-material-flex-layout-nhyrem?embed=1&file=src/app/app.component.html

#### What is the use-case or motivation for changing an existing behavior?
Imported components should be able to utilize flex-layout capabilities.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Not sure.  I've only tested on the latest versions of Angular.

#### Is there anything else we should know?
Although I have not tested it, I assume flex-layout works on imported components in general. Perhaps there is something different about importing for the root app.component?

**Comment by CaerusKaru** [comment]
I think you have a misunderstanding about how NgModules work. When a component is compiled at the module level, all of its dependencies needs to be present at compile-time in order to work. Once the module gets imported elsewhere, those references either exist or not in the imported module. Add FlexLayoutModule to your imported module and it should work fine.

**Comment by ebussa** [comment]
> Add FlexLayoutModule to your imported module and it should work fine.
@CaerusKaru That was it, thanks for the clarification.
