### ISSUE TITLE
FxLayoutGap grid mode not working

### ISSUE THREAD

**Issue by alexcoroza** [angular/flex-layout#1158]
# Bug Report

#### What is the expected behavior?
grid mode should add spaces between elements

#### What is the current behavior?
it adds space inside the element instead

#### What are the steps to reproduce?
Create a new angular 8 app with @angular/flex-layout@8.0.0-beta.27

https://stackblitz.com/edit/angular-zbzm2n

#### What is the use-case or motivation for changing an existing behavior?
I remember using it in my previous project(not sure if angular 6 or 7) and it is working but now its not. Need to add gaps between elements inside a fxlayout="row wrap" container

#### Is there anything else we should know?
I already read the documentation and it should add the gap "outside" and not "inside" the element

**Comment by MikaStark** [comment]
This isn't really an issue but a misunderstanding. fxLayoutGap in grid mode add a padding to the child elements (in your example `padding: 0px 10px 10px 0px;`) that's why it seems broken. To fix this you must wrap your child elements into a div with a `fxFlex` directive (with or without a value) like this

```html
<div fxLayout="row wrap" fxLayoutGap="10px grid">
  <div fxFlex>
    <button>asd</button>
  </div>
  <!-- the rest -->
</div>
```

To fit very nicely I recommand using css to force buttons to have 100% width.

I know, it's pretty annoying to use more wrapping containers but in grids world it helps alot ;)

**Comment by CaerusKaru** [comment]
@MikaStark is correct. Closing this issue as working as designed.
