### ISSUE TITLE
FxLayout="column" gives me flex-direction="row"

### ISSUE THREAD

**Issue by jvzaniolo** [angular/flex-layout#1221]
# Bug Report

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by m-malczyk** [comment]
fxLayout.xs="column" there is a column for small screens? This is expected I guess

**Comment by jvzaniolo** [comment]
I said that when I use fxLayout="column" the result on css is { flex-direction: row; }

**Comment by RobinKamps** [comment]
I have the same issue. fxLayout="column" does only work, if size is specified on fxLayout like fxLayout.lt-md, fxLayout.xs etc..
fxLayout="column" without any size does not work as described in the api https://github.com/angular/flex-layout/wiki/fxLayout-API

However: if you just add a point . to fxLayout it will work.
so a quick workaround is to use:
```fxLayout.="column"```
instead of
```fxLayout="column"```

Here a more clear stackblitz:
https://stackblitz.com/edit/angular-flex-layout-seed-mrrghk

... just change fxLayout="column" in line 9 to fxLayout.="column" to see what this issue is about.

**Comment by CaerusKaru** [comment]
According to the demo provided, this is working as intended. Adding `.` simply disabled the directive (since `fxLayout.` does not match to anything).

**Comment by RobinKamps** [comment]
Thank you,
sorry - this was a misunderstanding. 

For clarification:

Row means: all elements are side-by-side in "columns" in one row. 
Row does not mean: All elements are in separate rows beneath each other.
Column means: all elements are in one column beneath each other.
Column dows not mean: all elements are side-by-side in one row each in a separate column.
