### ISSUE TITLE
Extending responsive API with `gte` and `lte`

### ISSUE THREAD

**Issue by pmilic021** [angular/flex-layout#1224]
# Feature Request

#### What is the desired behavior?
To have `lte` and `gte` responsive selectors along with existing `lt` and `gt`.

#### What is the use-case or motivation for the desired behavior?
It's minor detail, but in order to cover all screen sizes it would be nicer to be able to write something like this:
`<div ngClass.lte-sm="example-mobile-class" ngClass.gt-sm="example-desktop-class">`
than this:
`<div ngClass.lt-md="example-mobile-class" ngClass.gt-sm="example-desktop-class">` .

#### Is there anything else we should know?
I could try to tackle it myself and make a PR if you agree it makes sense to implement this.

**Comment by CaerusKaru** [comment]
I think I might be missing the practicality here. lte-sm == lt-md. gte-sm == gt-xs. Is this truly needed?

**Comment by pmilic021** [comment]
Yeah, it is essentially an alias, and it's not truly needed (definitely low priority), but it would be nice to be able to write it in such fashion - noticed that some of the juniors in our company wrote `lt-sm` and `gt-sm` thinking they covered whole spectrum of sizes. Don't want to burden you core guys with it so I offered my help on it, if you deem it worthy the hassle.

**Comment by CaerusKaru** [comment]
It’s an interesting case for sure. My recommendation in the meantime is to implement it in your own project using custom breakpoints and report back on its effectiveness.

I’m wary to add new standard breakpoints to the library because it ends up adding significant size to the library. Each string literal has to be copied into all 20+ directives, and we’re already over-sized as it is. If #1185 ever goes through this would be a moot point, but until then that’s my biggest concern.

**Comment by pmilic021** [comment]
Agree, size is definitely more important than this, didn't even cross my mind. Anyway, if we find it useful, I'll reopen a ticket. Closing this one in the mean time.
