### ISSUE TITLE
bug([MatButtonModule,FlexLayoutModule]): Button below 17px—and thus invisible text—on Safari

### ISSUE THREAD

**Issue by SamuelMarks** [angular/flex-layout#1266]
#### Reproduction

https://stackblitz.com/edit/angular-ivy-4fjl3s

Steps to reproduce:
1. Open on Safari (tested with 13.1.1 (15609.2.9.1.2) on macOS)
2. Widen stackblitz rendered output Window
 
#### Expected Behavior

Every other browser I tried (Chrome, Firefox) shows the full button for every screen size.

#### Actual Behavior

Unable to see it:
<img width="567" alt="Screen Shot 2020-05-28 at 9 21 15 pm" src="https://user-images.githubusercontent.com/807580/83135446-300b4f00-a129-11ea-98c7-5124791137f8.png">

#### Environment

- Angular: 9.1.9
- CDK/Material: 9.2.4
- Browser: Safari 13.1.1 (15609.2.9.1.2)
- Operating System: macOS 10.15.5 (19F96)

**Comment by Splaktar** [comment]
This is due to how Safari handles flex differently. You have options as mentioned in the [fxFlex docs](https://github.com/angular/flex-layout/wiki/fxFlex-API):

You can solve this a few different ways
- instead of `fxFlex="100" on your `h3`, use `fxFlex="auto"`
- instead of `fxFlex="100" on your `h3`, use `fxFlex="1 1 0"`
- add `fxFlex="36px"` to your button

With `fxFlex="100"` you are telling the `h3` to take up 100% of the height, which leaves none for the button. The other browsers figure out that you probably didn't actually want that, but Safari tries to give you what you asked for, even if it means making the button unreadable.

**Comment by SamuelMarks** [comment]
Thanks… that did the trick.
