### ISSUE TITLE
FlexLayoutModule Not working with Angular 11

### ISSUE THREAD

**Issue by yunivrsl** [angular/flex-layout#1320]
# Bug Report

#### What is the expected behavior?
flex-layout: fxLayout; fxFlex, should provide layout structure based fxFlex on the page

#### What is the current behavior?
flex-layout is not working in angular 11

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://stackblitz.com/edit/flex-layout-seed-nightly) using latest `npm` nightly release: 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 11.1.1
Centos 7
Typescript 4.1.3
firefox 78.5.0esr

**Comment by CaerusKaru** [comment]
Please provide a minimal reproduction for this issue. For reference, all of our CI/CD uses Angular v11 without issue, as does our demo app.

**Comment by yunivrsl** [comment]
Please disregard.  it was VSCode issue.  restarting VSCode seem to have worked.

**Comment by irkreja** [comment]
`ng update @angular/cdk
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 36 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/cdk" (requires "^10.0.0-rc.0", would install "11.2.0").
✖ Migration failed: Incompatible peer dependencies found.
`

**Comment by mortalwind** [comment]
when running ng serve, I'm getting theese errors:
`Error: Failed to compile entry-point @angular/flex-layout/flex (es2015 as esm2015) due to compilation errors:
node_modules/@angular/flex-layout/esm2015/flex.js:180:7 - error NG2006: The directive DefaultLayoutDirective inherits its constructor from LayoutDirective, but the latter does not have an 
Angular decorator of its own. Dependency injection will not be able to resolve the parameters of LayoutDirective's constructor. Either add a @Directive decorator to LayoutDirective, or add an explicit constructor to DefaultLayoutDirective.

180 class DefaultLayoutDirective extends LayoutDirective {
          ~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/esm2015/flex.js:971:7 - error NG2006: The directive DefaultFlexOrderDirective inherits its constructor from FlexOrderDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of FlexOrderDirective's constructor. Either add a @Directive decorator to FlexOrderDirective, or add an explicit constructor to DefaultFlexOrderDirective.

971 class DefaultFlexOrderDirective extends FlexOrderDirective {
          ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/esm2015/flex.js:1095:7 - error NG2006: The directive DefaultFlexOffsetDirective inherits its constructor from FlexOffsetDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of FlexOffsetDirective's constructor. Either add a @Directive decorator to FlexOffsetDirective, or add an explicit constructor to DefaultFlexOffsetDirective.

1095 class DefaultFlexOffsetDirective extends FlexOffsetDirective {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/esm2015/flex.js:1194:7 - error NG2006: The directive DefaultFlexAlignDirective inherits its constructor from FlexAlignDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of FlexAlignDirective's constructor. Either add a @Directive decorator to FlexAlignDirective, or add an explicit constructor to DefaultFlexAlignDirective.

1194 class DefaultFlexAlignDirective extends FlexAlignDirective {
           ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/esm2015/flex.js:1455:7 - error NG2006: The directive DefaultLayoutAlignDirective inherits its constructor from LayoutAlignDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of LayoutAlignDirective's constructor. Either add a @Directive decorator to LayoutAlignDirective, or add an explicit constructor to DefaultLayoutAlignDirective.

1455 class DefaultLayoutAlignDirective extends LayoutAlignDirective {
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: Failed to compile entry-point @angular/flex-layout/grid (es2015 as esm2015) due to compilation errors:
node_modules/@angular/flex-layout/esm2015/grid.js:85:7 - error NG2006: The directive DefaultGridAlignDirective inherits its constructor from GridAlignDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of GridAlignDirective's constructor. Either add a @Directive decorator to GridAlignDirective, or add an explicit constructor to DefaultGridAlignDirective.

85 class DefaultGridAlignDirective extends GridAlignDirective {
         ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/esm2015/grid.js:523:7 - error NG2006: The directive DefaultGridAreaDirective inherits its constructor from GridAreaDirective, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of GridAreaDirective's constructor. Either add a @Directive decorator to GridAreaDirective, or add an explicit constructor to DefaultGridAreaDirective.

523 class DefaultGridAreaDirective extends GridAreaDirective {
          ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/esm2015/grid.js:818:7 - error NG2006: The directive DefaultGridColumnDirective inherits its constructor from GridColumnDirective, but the latter does not 
have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of GridColumnDirective's constructor. Either add a @Directive decorator to GridColumnDirective, or add an explicit constructor to DefaultGridColumnDirective.

818 class DefaultGridColumnDirective extends GridColumnDirective {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/flex-layout/esm2015/grid.js:1121:7 - error NG2006: The directive DefaultGridRowDirective inherits its constructor from GridRowDirective, but the latter does not have 
an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of GridRowDirective's constructor. Either add a @Directive decorator to GridRowDirective, or add an explicit constructor to DefaultGridRowDirective.
`
