### ISSUE TITLE
fxLayoutAlign center does not set align-items: center;

### ISSUE THREAD

**Issue by spiotr12** [angular/flex-layout#1323]
# Bug Report

#### What is the expected behavior?
fxLayoutAlign="center" should set "align-items: center; align-content: center"

#### What is the current behavior?

![image](https://user-images.githubusercontent.com/10038964/109293357-f6888100-782b-11eb-997e-2020b68c0b4f.png)

No: `justify-content: center`
No: `align-items: center; align-content: center`

#### What are the steps to reproduce?
```
<h2 mat-dialog-title fxLayout="row" fxLayoutAlign="center">
  <span>{{title}}</span>
  <span fxFlex="auto"></span>
  <mat-icon *ngIf="titleIcon" [svgIcon]="titleIcon" [color]="titleIconColor"></mat-icon>
</h2>
```

#### What is the use-case or motivation for changing an existing behavior?
Feature works differently than the documentation

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

    "@angular/core": "~11.2.0",
    "@angular/flex-layout": "^11.0.0-beta.33",

**Comment by mackelito** [comment]
Have you tried `<mat-toolbar color="primary" fxLayout="row" fxLayoutAlign="center center">`... same issue?

**Comment by gajevski** [comment]
@mackelito Yes, unfortunately it doesn't solve the issue

**Comment by mackelito** [comment]
Could you create a stackblitz to reproduce the issue?
https://stackblitz.com/edit/flex-layout-seed-nightly

**Comment by DuncanFaulkner** [comment]
I couldn't get the stackblitz sample to work, I'm trying to understand your issue as I'm learning about the library and hoping I can help. My understanding of the issue, so I apologise now if I'm not completely correct.

```
<mat-toolbar color="primary" fxLayout="row" fxLayoutAlign="center">
  <mat-icon svgIcon="settings" color="primary"></mat-icon
></mat-toolbar>
```
you are expecting this to be in the centre of the toolbar? 

This doesn't centre because the default is "centre  stretch" which does place this in the centre width-wise, but not vertically. For this to be centred (horizontally and vertically) I think you need to specify the second value.

as in this example
```
<mat-toolbar color="primary" fxLayout="row" fxLayoutAlign="center center">
  <mat-icon
    style="outline: 1px solid white"
    svgIcon="settings"
    color="primary"
  ></mat-icon
></mat-toolbar>
```

likewise to be centred at the start
```
<mat-toolbar color="primary" fxLayout="row" fxLayoutAlign="start center">
  <mat-icon
    style="outline: 1px solid white"
    svgIcon="settings"
    color="primary"
  ></mat-icon
></mat-toolbar>
```

and centred at the end 
```
<mat-toolbar color="primary" fxLayout="row" fxLayoutAlign="end center">
  <mat-icon
    style="outline: 1px solid white"
    svgIcon="settings"
    color="primary"
  ></mat-icon
></mat-toolbar>
```
Please let me know if this helps

**Comment by mackelito** [comment]
@spiotr12 your issue is the fxFlex="auto" property... it will force the other elements to the sides
@gajevski Are you sure you have imported the Module? Take a look at the element and see if there are inline styles added or not..

Here's stackblitz that show's that it does work :)
Also added some other examples ;)

https://stackblitz.com/edit/angular-cmnwmx-vr6uv7?file=src%2Fapp%2Ftoolbar-basic-example.html

**Comment by lmejiafrt** [comment]
@spiotr12  did you import the FlexLayoutModule in your main app file? It works for me!!!

**Comment by CaerusKaru** [comment]
I'm going to close this as @mackelito is correct, and this issue has been stale for several months. Thank you @mackelito, as always.
