### ISSUE TITLE
StyleUtils._applyMultiValueStyleToElement Cannot read property 'setProperty' of undefined

### ISSUE THREAD

**Issue by michelevirgilio** [angular/flex-layout#1335]
# Bug Report

#### What is the expected behavior?
No errors

#### What is the current behavior?
I get the error 'Cannot read property 'setProperty' of undefined'

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
10.0.4

the problematic code is 
https://github.com/angular/flex-layout/blob/9618c7bb5b423ed17e9e25f3a6315343a2660d1a/src/lib/core/style-utils/style-utils.ts#L124

it is trying to set style for an ng-reflect-* comment such as
```
<!--bindings={
  "ng-reflect-icon": "something"
}-->
```

I think it should check if `element.style` is defined.
Thanks

**Comment by CaerusKaru** [comment]
Can you provide a real reproduction of this issue? I have no way of telling what context this error occurs in otherwise. Element.style is something that should be present on any element that Angular Layout supports. If it is not, it implies that Flex Layout does not work with that element. If you find a case where this is not true, please specify it here and we can investigate. Otherwise we will close this issue.

**Comment by aminesafi8** [comment]
This problem occurs when you use one of the **FlexLayout directive** (fxLayout, fxLayoutAlign, ...) on an `<ng-container>` tag
Please delete it from this tag and use the directives on a div or any other html tag instead.

**Comment by michelevirgilio** [comment]
Hi, thanks for replies. Why ng-container would not be supported?

**Comment by CaerusKaru** [comment]
`ng-container` is not a DOM element. This library only works with DOM elements (or components that get turned into DOM elements).
