### ISSUE TITLE
Support for Angular 15

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/flex-layout#1430]
When will Angular 15 be supported?
If we install `14.0.0-beta.41` it is throwing peer dependency issues.

**Comment by arambazamba** [comment]
I understand the part about clean css … But loosing alls the responsive media query aliases like .lt-md … and writing tons of media queries instead is simply a nightmare … I also have to mention that mateial:mdc update does not make thinks look better. I also wonder how to set the SideNav Position without MediaObserver … Very disappointing and lots of work for nothing!!

**Comment by alan-agius4** [comment]
@mattiLeBlanc, `@angular/flex-layout` is in LTS and the Angular team will stop publishing new releases of this experimental  library starting in v15.

**Comment by Maxxxell** [comment]
Stopping support Flex Layout is simply insane!

**Comment by mattiLeBlanc** [comment]
I thought that the flex-layout lib added styles inline via javascript. So how would this result in a large CSS footprint?
I also regret seeing FlexLayout go, I think it is a very use library for positioning my View elements.

**Comment by alexhendel** [comment]
There already is a branch for Angular 15 support and a [PR](https://github.com/angular/flex-layout/pull/1431). So I am guessing a flex layout package will have a new version soon.

**Comment by CaerusKaru** [comment]
@alexhendel is correct, we will publish a v15 version. This will unpin the dependencies so, barring any structural breaking changes, this will not happen in the near future. We hope to get this version out this coming week.

**Comment by jpike88** [comment]
@alan-agius4 This library is 6 years old, and under the official angular namespace. It is averaging 352k downloads a week. How are you able to call it 'experimental' with a straight face? Normally, experimental projects say they are experimental, and it kind of loses that label when it's more than 10% the weekly downloads of @angular/cli itself.

Seriously, wtf?

**Comment by alan-agius4** [comment]
> This library is 6 years old, and under the official angular namespace. It is averaging 352k downloads a week. How are you able to call it 'experimental' with a straight face? 

I can understand the confusion due to the usage of the namespace.  This package however was always driven and maintained by the community. And while it was released for 6 years, the package was never released as a stable version. It was always released as non stable version with a beta suffix.

> Normally, experimental projects say they are experimental, and it kind of loses that label when it's more than 10% the weekly downloads of @angular/cli itself.

Not really sure where you got your stats from.

<img width="374" alt="Screenshot 2022-11-21 at 14 59 44" src="https://user-images.githubusercontent.com/17563226/203073668-0271bd3c-bf5a-40da-ac93-06c1286ad8fa.png">

<img width="368" alt="Screenshot 2022-11-21 at 14 59 48" src="https://user-images.githubusercontent.com/17563226/203073672-9d07fd79-bbb9-47f7-827b-f45a613a4fc4.png">




But the downloads per week would not change that the fact that the package was never released as stable. A beta package even if it is downloaded downloaded 700 millions times / week remains a beta package.

**Comment by mtabaj** [comment]
@alan-agius4 I can't understand the angular team nor Google.
 There are thousands of projects using this library, to review everything is almost impossible.  So it means that A LOT of projects will stop continue with futures releases of Angular.
All the signs you emit are in the direction to stop using angular : flutter, without typescript and not using Material Design, etc.
Many developers are changing to React, and you are encouraging to accelerate this movement.

**Comment by Franweb79** [comment]
[lan-agius4](https://github.com/alan-agius4) You are only showing us that we can´t trust Angular team. What will be next, angular material? 

Is this  your idea of "We recognize that you need stability from the Angular framework. Stability ensures that reusable components and libraries, tutorials, tools, and learned practices don't become obsolete unexpectedly. Stability is essential for the ecosystem around Angular to thrive"?

Because you are doping the opposite. This shows a total lack of respect for Angular users and maybe as @mtabaj says, is a good moment to think about switching to React.

**Comment by sandrumirceaioan** [comment]
I guess we should start by fixing all the apps for our clients with "modern CSS", then go give React a try...

**Comment by twerske** [comment]
This conversation has strayed from the original topic regarding support for Angular v15 and I want to remind people commenting of the [Code of Conduct](https://github.com/angular/flex-layout/issues/1430#issuecomment-1321320073).

As @CaerusKaru mentioned, [a deprecated v15 support is in progress](https://github.com/angular/flex-layout/issues/1430#issuecomment-1321320073) and the package is in LTS per our announcements [here](https://blog.angular.io/modern-css-in-angular-layouts-4a259dca9127) and [here](https://medium.com/@caerus.karu/farewell-flex-layout-aaa567023769).

I understand the frustrations you shared. While the package is `beta` and does not fall under our [release backwards compatibility commitment scope](https://angular.io/guide/releases), we understand how many users rely on it. I personally think it's a signal of the team's commitment to community and stability that we are committed to providing LTS support for at least one year while users plan for [migrations](https://github.com/angular/flex-layout/issues/1426).

**Comment by CaerusKaru** [comment]
I apologize for the delay, and also for locking down this issue. The comments here were getting too heated. That being said, after much work on our end, we have unblocked the v15 release. Now we are just waiting until the holidays end and everyone is back from break so that we can cut a release. We appreciate your patience in the meantime. It's been a frustrating process for us as well.

**Comment by CaerusKaru** [comment]
Beta 42 with support for Angular v15 is live on NPM. Thank you all again for your patience as we've had to navigate a rather unusual past few months.
