### ISSUE TITLE
Class directive not applied correctly for ngFor and ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by dfmartin** [angular/flex-layout#206]
I am trying to use ChangeDetectionStrategy.OnPush along with an ngFor, but have found that the class/ngClass directive does not work when using OnPush.  What I am finding is that the appropriate class is being applied to **only** the last item in the list.

This occurs only on the initial render.  If the screen is resized to cause a change then everything works from that point forward.  I have tried ChangeDetectorRef.markForCheck() and seen no change.  One thing that causes some head scratching is that the class **is** applied to the last item so it's obvious the class directive is firing correctly somewhere.

I have put up a plunker (appropriated from a demo for side nav).  If you look at the file `src/app/responsive-sidenav.ts` . There is a line in the meta that can be commented out to see the "correct" behavior.

http://plnkr.co/edit/zalFNqqiznHUyg33FJII?p=preview

**Comment by ThomasBurleson** [comment]
This will be fixed with PR https://github.com/angular/flex-layout/pull/223/files.

Also here is a [working version](http://plnkr.co/edit/jCICQ1GXFnzFqFTFlXwh?p=preview) of your Plunkr (with the latest code).

*  Note the html `<div class='item' ngClass.gt-xs='item showOnGtXs'>` 
*  Note the css 
```css
.item.showOnGtXs {
  color: #932e2e;
  background-color: #DDECFE
}
```

Here are some docs explaining how to add/remove/merge classes: https://github.com/angular/flex-layout/wiki/ngClass-API#responsive-features

**Comment by ThomasBurleson** [comment]
So I fixed other issues. But not the initial-pageload-ngFor issue.

**Comment by ThomasBurleson** [comment]
Reopen since the ngFor issue is still present.

**Comment by ThomasBurleson** [comment]
@dfmartin - see working Plunkr  https://plnkr.co/edit/jCICQ1GXFnzFqFTFlXwh?p=preview

> uses local snapshot build of the PR `flex-layout.umd.js`
