### ISSUE TITLE
fxShow not working

### ISSUE THREAD

**Issue by whyao** [angular/flex-layout#216]
Hey, I tried to use fxShow in one of your examples and it doesn't seem to be working properly. fxHide works when I do:

`fxHide.xs="true"`

but fxShow doesn't work when I do:

`fxShow.gt-xs="true"`

```html
<button class="nav-trigger" 
            (click)="toggleMenu()" 
            color="primary" 
            md-icon-button>
     Toggle Button
</button>

<div [fxShow]="menuOpen"
     fxShow.xs="true"
     style="margin-top:25px;background-color:#d9edf7">
  I should hide and show
</div>  
```

[https://plnkr.co/edit/3SKnjiop1QSXZaKjxHAQ?p=preview](https://plnkr.co/edit/3SKnjiop1QSXZaKjxHAQ?p=preview)

**Comment by bobrosoft** [comment]
See the same issue with next markup:
```
<span fxShow [fxShow.gt-xs]="true">Visible on desktop</span>
```
Do I use it right? Btw @whyao your code looks different to documentation.

**Comment by bobrosoft** [comment]
Next code is working:
```
<span fxHide [fxHide.gt-xs]="false">Visible on desktop</span>
```
I think there's some confusion in documentation language or need more examples...
Explanation for example above: `fxHide` will hide element for all sizes, `[fxHide.gt-xs]="false"` will not hide element for `gt-xs`. Rules applied from left to right, following rules overrides previous ones.

**Comment by bobrosoft** [comment]
Opposite example: 
```
<span fxShow [fxShow.gt-xs]="false">Visible on mobile</span>
```
I think all is working btw, not a bug. @ThomasBurleson can you confirm?

**Comment by ThomasBurleson** [comment]
@whyao - this is working with the latest code in HEAD (on master).

* [Working Plunkr](https://embed.plnkr.co/Hfl9wS7DffbNWXudGzvu/)
  * Do not use `FlexLayoutModule.forRoot()`...  use `FlexLayoutModule`
  * To use the latest build code (pre-release), update your config
     *  `'@angular/flex-layout' : 'https://rawgit.com/angular/flex-layout-builds/master/bundles/flex-layout.umd.js'`

---- 
####  fxShow/fxHide Rules

Flex-Layout supports static API for responsive layouts  using the API **without** `.<xxx>` alias suffices: fxShow, fxHide, etc. These are applied regardless of the viewport size; unless overrriden by a registered adaptive API.

*  fxHide (without a value) means "display:none"
*  fxHide="false" means use the original display value (should no longer be hidden)
*  fxShow (without a value) means use the origin display style value
*  fxShow="false" means "display:none" and hide it.

> fxHide is the inverse of fxShow 

Flex-Layout support API for dynamic **Adaptive** layouts using the the API with mediaQuery aliase suffices. e.g.  fxShow**.gt-sm**, fxHide**.lg**, etc.  

When a mediaQuery range activates, the directive instances will be notified. If the current activate mediaQuery range (and its associated alias) are not used, then the static API value is restored as the fallback value.

The *fallback* solution uses a **`largest_range-to-smallest_range`** search algorithm. Consider the following:

```html
<div fxShow.sm="false"  fxShow.gt-md="false" fxShow="true" ></div>
```

*  When the `lg` range is activated (by viewport resizing,etc) the div is **hidden** since the `gt-md` is used as the closest descending fallback value.
*  When the `md` range is activated, the div is **shown** since the static API is the closest descending matching condition.
*  When the `sm` range is activated the div is **hidden**.

> Please note that there is no left-to-right precedence. This is an incorrect interpretation..
