### ISSUE TITLE
feat(breakpoints): only apply flex properties if a breakpoint is activated

### ISSUE THREAD

**Issue by jeffbcross** [angular/flex-layout#296]
(opening issue per @ThomasBurleson suggestion in #201)

My comment:

> I'd like to be able disable flex layout completely for some elements when the width is extra small. But right now, even if I use gt-xs breakpoints, flex CSS properties are being added to the elements.
>
> 
> ```html
> <div fxLayoutAlign.gt-xs="center" fxLayout.gt-xs="row" fxLayoutGap.gt-xs="25px">
>   <div fxFlex.gt-xs="500px" class="victor"></div>
> </div>
> ```
>
> The layout element has `display: flex; flex-direction: row;` and the "victor" element has `flex: 1 1 0 0.00000001px;` when the width is xs. I expected that using only `gt-xs`, and no defaults, would mean that the flex properties would only be applied when the screen was greater than xs.

For further context, the main motivation is for a responsive layout where I want rows to be columns (stacked) on mobile. Safari has requirement of parent column containers having a set height (not auto), or else elements start clobbering each other. I want the child elements to be `display: block; height: auto;`.

Thanks :)

**Comment by jeffbcross** [comment]
BTW happy to submit a PR if maintainers agree with the request and we can agree on a design, but I'm guessing this would require significant internal changes.

**Comment by ThomasBurleson** [comment]
@jeffbcross - When using the flex-layout API, if you use responsive directives WITHOUT default flex-layout directives, then those defaults are **injected** as needed.

So - in your scenario above - the following is what is actually happening:

```html
<div fxLayout="row"
     fxLayoutAlign="start start"
     fxLayoutGap="0px"
     
     fxLayout.gt-xs="row" 
     fxLayoutAlign.gt-xs="center" 
     fxLayoutGap.gt-xs="25px">

  <div fxFlex
       fxFlex.gt-xs="500px" 
       class="victor"></div>

</div>
```

Now if you have CSS define for `flex-direction:column` then the default fxLayout will use that...
We presume defaults because those values are restored when a responsive breakpoint **de-activates".

Closing as non-issue.

**Comment by ThomasBurleson** [comment]
@jeffbcross - The current architecture assumption is that any responsive API usage implies that the host element will have default (non-responsive) flexbox settings auto-applied . 

Under what scenarios would you want the container `box` to NOT have default flexbox settings when you specified such for mobile? 

```
<div class="box" fxLayout.gt-xs="row"></div>
```

**Comment by matheusdavidson** [comment]
@ThomasBurleson I think this should be considered, i mean, if you use ```fxFlex.gt-xs``` or ```fxLayout.gt-xs```or any other property with a breakpoint, you expect flex layout to apply the properties only in those espcified breakpoints.

Even more for those(like me) who use this API since material 1, when you would only get what you declared in your HTML.

**Comment by ThomasBurleson** [comment]
@matheusdavidson - agreed. This is in the queue for Beta.10 fix.

**Comment by matheusdavidson** [comment]
For other people seeing this, the workaround for now, at least for ```fxFlex``` is to set ```fxFlex="none"``` as default

**Comment by matheusdavidson** [comment]
@ThomasBurleson, i think the best thing to do is not have a default at all. Apply the style only in the breakpoint specified. If one wants a default value, its easy, just use without any breakpoint(fxFlex). 

For example, if i want to use ```fxFlex```only in ```xs```, i would expect the styles being added only when i specify ```fxFlex.xs```, when the breakpoint is outside of ```xs``` no style is inserted, right now the default style will break the layout specially in IOS, because its adding extra style that developers don't expect.

**I think is much better this way:**
1) Scenario where i want style only for ```xs``` and **no default** for any other breakpoint:
```<div fxFlex.xs></div>```
```<div fxLayout.xs></div>```

2) Scenario where i want specific style for ```xs```and a **default style** for all other breakpoints:
```<div fxFlex fxFlex.xs="none"></div>```
```<div fxLayout="row" fxLayout.xs="column"></div>```

**Comment by matheusdavidson** [comment]
Chrome won't care much about this, the layout won't break, but look what happens in Safari/IOS with the extra styles i didn't expect(first image is the broken one, second is the fixed one with fxFlex="none"):

**Wrong**
![image](https://user-images.githubusercontent.com/2229994/29803514-cfb6a110-8c52-11e7-99d9-01561874e463.png)

**Fixed with fxFlex="none"**
![image](https://user-images.githubusercontent.com/2229994/29803572-3ce148d0-8c53-11e7-9135-8a65397a155a.png)

**Comment by ThomasBurleson** [comment]
@matheusdavidson - if `fxFlex` is not defined, then defaulting to `fxFlex="none"` is a reasonable solution.
