### ISSUE TITLE
question: ie support

### ISSUE THREAD

**Issue by mmrath** [angular/flex-layout#32]
Would this library be supported on ie 11?

**Comment by ThomasBurleson** [comment]
See http://caniuse.com/#feat=flexbox  

> IE 11 has partial support is due to large amount of bugs present (see known issues):

- IE 11 requires a unit to be added to the third argument, the flex-basis property see MSFT documentation
- In IE10 and IE11, containers with display: flex and flex-direction: column will not properly calculate their flexed childrens' sizes if the container has min-height but no explicit height property. See bug.
- In IE 10, setting -ms-flex-flow: row wrap will not wrap unless display: inline-block is set on child elements.
- IE 11 does not vertically align items correctly when min-height is used see bug
- In IE10 the default value for flex is 0 0 auto rather than 0 1 auto as defined in the latest spec.

> Efforts to improve flex-layout to account for [Known Flex Bugs](https://github.com/philipwalton/flexbugs) is in-progress.
