### ISSUE TITLE
Links in API Documentation aren't correct

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#334]
On https://github.com/angular/flex-layout/wiki/API-Documentation

The links to fxFlexOrder, fxFlexOffset, fxFlexAlign and fxFlexFill all take me (via redirect) to the wiki homepage (https://github.com/angular/flex-layout/wiki) rather than any documentation about those specific attributes.

**Comment by nickprivalov** [comment]
It would really be helpful if a lot of the links were directed to detailed articles on those attributes.  A lot of the time some more detail is needed to better understand how to use the Flex Layout instead of being left to throw things at a wall repeatedly and lose time.

**Comment by fazpu** [comment]
fxLayoutWrap and fxLayoutAlign are not working as well

**Comment by fazpu** [comment]
Also, I find it very confusing that the incorrect links are pointing to non-existent documents. Hence, it is tempting to check the github wiki if there are the documents, only under different path. And they are not :-)
It would be much better if there were no links at all in such cases.

**Comment by nermand** [comment]
Link to the source of the fxLayout directive on
https://github.com/angular/flex-layout/wiki/fxLayout-API
is also broken. 
Instead of
https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/layout.ts#L60-L69
it should be pointing to the
https://github.com/angular/flex-layout/blob/master/src/lib/api/flexbox/layout.ts#L53-L69

**Comment by ThomasBurleson** [comment]
Fixed with SHA 67e4bf5bccc0ade
