### ISSUE TITLE
Does ngStyle/ngClass support `lt-xx` `gt-xx` postfix?

### ISSUE THREAD

**Issue by naivefun** [angular/flex-layout#343]
In my test it does not work but I do not see any statement that it should not work.
```html
        <div style="padding-top: 1em;"
             ngStyle.gt-lg="width: 'calc(33.33% - 15px)'; 'padding-top': '1em';"
             [style.md]="{width: 'calc(50% - 15px)'}"
             [style.sm]="{width: 'calc(100% - 15px)'}"
             [style.xs]="{width: 'calc(100% - 15px)'}"></div>
```

**Comment by ThomasBurleson** [comment]
See https://github.com/angular/flex-layout/blob/master/src/lib/flexbox/api/style.ts#L86-L100.
This should be working. Please provide a [Plunkr](https://plnkr.co/edit/h8hzyoEyqdCXmTBA7DfK?p=preview) that demonstrates it not working.

**Comment by ThomasBurleson** [comment]
Closing as not-an-issue.

**Comment by Juliozen** [comment]
Hello Guys!! I am really in trouble with this.
I user this Dependencies:
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/flex-layout": "^2.0.0-beta.10",
    "@angular/forms": "^4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/platform-server": "4.1.3",
    "@angular/router": "4.1.3",

"devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "4.1.3",


As you see i use  "@angular/flex-layout": "^2.0.0-beta.10", i simple i CAN`T use [ngStyle.lt-sm]="'min-height: 800px;'"

My console.log is:

Can't bind to 'ngStyle.lt-sm' since it isn't a known property of 'div'. ("<div class="box-container" fxLayout="column"  [ERROR ->][ngStyle.lt-sm]="'min-height: 800px;'">




i can still use style="min-height: 800px", etc... but this solution dosnt give the reponsive feature to my system.

I use angular to be responsive and all platforms (as well).... So what should i do Guys?? Any one please can help me? Have a nice day if u read all....!

**Comment by maddy2308** [comment]
hello @Juliozen were you able to resolve the issue that you had, I am facing a similar issue now. Below are my dependencies
`
"dependencies": {
    "@angular-devkit/core": "^0.2.0",
    "@angular/animations": "^5.0.1",
    "@angular/cdk": "5.0.0-rc.3",
    "@angular/common": "^5.0.1",
    "@angular/compiler": "^5.0.1",
    "@angular/compiler-cli": "^5.0.1",
    "@angular/core": "^5.0.1",
    "@angular/flex-layout": "^2.0.0-beta.10",
    "@angular/forms": "^5.0.1",
    "@angular/http": "^5.0.1",
    "@angular/material": "5.0.0-rc.3",
    "@angular/platform-browser": "^5.0.1",
    "@angular/platform-browser-dynamic": "^5.0.1",
    "@angular/platform-server": "^5.0.1",
    "@angular/router": "^5.0.1",
},
"devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.2.4",
    "@angular/language-service": "^5.0.0",
}
`
