### ISSUE TITLE
Print media support needed

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#361]
Flex-layout responsive breakpoints not working on print media. 

My pages look awful on `@media print`. Initial investigation reveals that at least `fxFlex.gt-xs="..."` isn't working when emulating CSS print media. What is this project's stance on supporting print media? I haven't seen anything in the docs.

[Here's a quick plunkr](https://plnkr.co/edit/5Cs8QhRb48sYzk2FqVP2?p=preview). Make the preview big to activate `gt-xs`, and then emulate print CSS media in Chrome.

**Comment by CaerusKaru** [comment]
@adamdport I know this is going to seem random because this issue has been closed for over a year, but could you provide an updated version of your example (possibly in StackBlitz) with the same versions from this one? If not I understand, but we're looking into changing how the library handles print events in a big way, and I don't want to miss this.

**Comment by adamdport** [comment]
@CaerusKaru I used your stackblitz starter from the "new issues" template and copied over the template and the CSS. Emulating the "print" CSS media in chrome seems to work fine, but the print preview shows the missing class. I'm not sure how many pixels a printed page is computed to be to know if it's correct or not.  https://stackblitz.com/edit/angular-flex-layout-seed-a6btyn

**Comment by CaerusKaru** [comment]
I've reverted that template to use the same version from the Plunkr (2.0.0-beta.8 – oh how time passes), and I'm seeing similar results. Do you recall what looked so bad in the original issue? (The Plunkr won't render for me)

**Comment by adamdport** [comment]
@CaerusKaru the orange element in the last row has an `ngClass.gt-xs` on it. On small screens it's 33% and has a white space next to it. On gt-xs it has 67% and doesn't have the white space. The original demo was meant to show that in print, it was showing the white space no matter what (`ngClass.gt-xs` was never activating). does that make sense?

**Comment by CaerusKaru** [comment]
Ok I get it now, this clears up a lot. Here's the root cause analysis: when the breakpoints were `screen and <breakpoint>`, and a print event fired, all of those breakpoints would be sent a _deactivation_ event, resulting in the fallback styles being applied (in the case of gt-xs, it would fallback on the regular ngClass). The patch here made it so that the breakpoints would still deactivate, but would _reactivate_ on whatever size the browser deems matches the print window.

The solution, which is much easier after the latest refactor, is to _intercept_ print events, and do nothing until they're over (or allow for custom behavior).

Thank you again for the insight here, it's helped us a lot in our future planning.
