### ISSUE TITLE
fix(package.json): Update dependency to use Angular 2.4.0

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/flex-layout#45]
**flex-layout** needs this [Angular Fix](https://github.com/angular/angular/commit/3bee521aa4465b1e389be02e1ef2e4a1e3a8bebc) in angular/#master`: fixed to support #34. 

* v2.3.x and higher also provides support for important [Component Inheritance](https://scotch.io/tutorials/component-inheritance-in-angular-2)

> flex-layout package.json's should be updated once  ng v2.4.0 is available.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 608c5c1e3079461f0ea245162fb4daca9342b1ad

**Comment by pdavin** [comment]
The NPM peer dependencies still say @angular/flex-layout depends on Angular ^2.2.3.  Should that say 2.4.0?  
$ npm view @angular/flex-layout

I'm having trouble linking flex-layout into my AoT build (ngc is hitting compilation errors in flex-layout) and am wondering if it's due to the fact I'm still on Angular 2.2.4.

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/angular-flex-layout)
*  [Gitter Channel](https://gitter.im/angular/flex-layout) - note this will be available soon...

Closing this issue as 'invalid'. Thank you.
