### ISSUE TITLE
Peer Dependency Error With FlexLayout On Angular5

### ISSUE THREAD

**Issue by Iam-jegan** [angular/flex-layout#519]
#### Bug, feature request, or proposal:
I get peer dependency error while doing npm install of flex-layout

#### What is the expected behavior?
Should be able to install the flex-layout without any dependency error.

#### What is the current behavior?
Throws peer Dependency error.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 
Just create a brand new Angular 5 app. then do npm install of flex-layout
"@angular/flex-layout": "^2.0.0-beta.10-4905443"

#### What is the use-case or motivation for changing an existing behavior?
I want to use Angular 5 with flexlayout

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5, Angular Material 5

#### Is there anything else we should know?

HERE BELOW ARE THE ERROR LOGS: 
Now it appears to be warning.. but when I deploy to my cloud environment it throws error.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/
core@~4.4.4 but none was installed.
npm WARN @angular/flex-layout@2.0.0-beta.10-4905443 requires a peer of @angular/
common@~4.4.4 but none was installed.
npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-
beta <5.0.0 but none was installed.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta
 <5.0.0 but none was installed.
npm WARN @walmart/prcui@0.0.8 No license field.

**Comment by jotatoledo** [comment]
Dup #489

**Comment by aaronglang** [comment]
@Iam-jegan 
you can manually change the `"codelyzer"@"~3.2.2",` to `"codelyzer": "~4.0.1",` in your package.json and run npm install again. That should clear any codelyzer warnings.
Still not sure how to get the flex layout to work. Any help would be appreciated.

**Comment by Son-Lam** [comment]
Is there any plan to upgrade to Angular 5 soon?

Thanks,

**Comment by CharlieMisner** [comment]
+1... An approximate ETA would be really helpful.

**Comment by spock123** [comment]
I'm not sure an ETA would help.. I've seen lots of ETAs come and go. 
I remember seeing a post 3-4 weeks ago about an imminent release within a day or two. Nothing happened. Really frustrating. I know this is an open source project but being inside the @angular umbrella I would have expected more.  We are dependent on this library but we're now migrating away, too scarred to be good.

**Comment by viewstack** [comment]
For folks who are migrating away from flex-layout, what are you using instead ? I am relying on flex-layout as well and am concerned with the lack of progress on basic things like keeping sync with core angular, and would like to explore other options.

**Comment by spock123** [comment]
@viewstack sadly we're going back to the Bootstrap grid system. Also been looking into Css:Grid, but these 2 don't provide the same powers as @angular/flexbox, for example Observables  to watch out for changes in resolution etc.

For the most part, we can live with Bootstrap4 grid, it works great next to @angular/material.

Check this repo:

https://github.com/m-spyratos/bootstrap-4-grid

I still think @angular/flex-layout is a far superior solution, but it's been too rocky for me to use in our production builds. I need to be able to sleep at night :)
Maybe we can address it later on in 2018 if the project gets up and running again.

**Comment by kylecordes** [comment]
Another option we've been working with, is to use unassisted CSS flex layout, while this library is in development. CSS flex syntax is not too difficult, although the flex-layout library improves the ergonomics considerably.

**Comment by viewstack** [comment]
Thanks for the alternatives. Using css flex layout straight up should work for my use case mostly, I think. Any idea what the status of flex-layout is? Has it been officially abandoned or put on hold?

**Comment by kylecordes** [comment]
@viewstack Flex-layout appears to be a relatively minor project among the Angular family of projects. From looking at the commit history, it looks like mostly one (really, really sharp!) person outside Google is working on it, not a team at Google. So it's not uncommon to have a lull in activity. People get busy and distracted from open source efforts, it certainly happens to everything open-source I work on :-)

Of course it would be fantastic to eventually have a more formal, "first party" Google maintained solution for layout in the box. As I understand, both CLI and Universal started out as outside, volunteer efforts and have been since adopted by the core team. Maybe a layout library might eventually follow along that path.

**Comment by abeymg** [comment]
@kylecordes : That's good to know. I had not realized that the flex-layout project had no core angular team members participating. I assumed there was, because of its inclusion in the @angular package. I internally had assumed angular material and flex-layout were being worked on by the same team. This explains why the releases are not in synch. I guess I have some thinking to do... :)
