### ISSUE TITLE
Beta 11 not published to NPM

### ISSUE THREAD

**Issue by nueko** [angular/flex-layout#522]
Hello, am I missing or is that intended that beta 11 not published yet?

thanks

**Comment by Stephane-Peyroutet** [comment]
Could you please close this one in order to keep the repo clean.

Indeed, there are already a ton of opened issues regarding the same problem or some related ones :
 - #511, #508, #507, #494, #489, #479 

You can have more info on the last one (479) and @ThomasBurleson is taking care of this.
Hopefully, all these issues should be closed after the beta.12 release.

**Comment by jotatoledo** [comment]
Search for issues with same problems before creating a new one

**Comment by cebor** [comment]
Is @ThomasBurleson even alive? 😄

**Comment by javahaxxor** [comment]
That guy is a hard worker, does a s__toad of commits Saturdays, Sundays,
and even if I'd like to see some issues fixed, I'd sleep better if I knew
he was on a beach somewhere sipping on a beer


Is @ThomasBurleson <https://github.com/thomasburleson> even alive? 😄
