### ISSUE TITLE
Feature Request: use width instead of max-width

### ISSUE THREAD

**Issue by MarcusMorba** [angular/flex-layout#538]
#### Bug, feature request, or proposal:
feature request: setting to use "width" instead of "max-width" in the inline -style.

#### What is the expected behavior?
Be able to add classes using min-width or max-width

#### What is the current behavior?
Inline styles overwrites the css-class settings.

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

#### What is the use-case or motivation for changing an existing behavior?
Depending on the breakpoints I want to define a min-width which is bigger than the default percentage value set via "fxFlex="20": e.g. "... div fxFlex="20" ngClass.lt-lg="fixedWidth_2col" ..."

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4.1

**Comment by stellasoft-will** [comment]
Also when using a calc(25% -20px) this does not apply max-width or to this guys preference width which would solve "better way of handling gap/gutter #134"

**Comment by CaerusKaru** [comment]
Alright, I've looked into this pretty heavily, and this is unlikely to happen. It would throw off basically every flex styling we need. You can see for yourself by applying `width` instead of `max-width` to the demos in the demo app. They look terrible.

Some clarification on this issue can be found [here](http://gedd.ski/post/the-difference-between-width-and-flex-basis/).

If you really need your classes to set `max-width`, I suggest styling with an `!important` priority on the rules. In the future, we may move to class-based stylings to have reduced specificity, but for the time being, I think this is where this issue stands.

I'll follow-up with @ThomasBurleson next week, but this issue is moot until then.

**Comment by MarcusMorba** [comment]
"!important" is what I have used by now, but the need to use it is really bad way of writing CSS/SCSS. I need to check the newer versions, but as our development is currently with Angular 4.x, I mostly use the latest working beta version 10/11. So close it for now.
