### ISSUE TITLE
Why does the fxFlexFill not working as expected?

### ISSUE THREAD

**Issue by wizzardz** [angular/flex-layout#557]
#### Bug, feature request, or proposal:
When fxFlexFill is applied to a component it should take the whole height of the parent, but it does not seems to be working. 

#### What is the expected behavior?

The element should take the height of the parent.

#### What is the current behavior?

The element is taking the height of its contents (child elements).

![image](https://user-images.githubusercontent.com/8329475/34819296-59220f98-f6e3-11e7-817c-dfc49945dd64.png)

#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

Please find the demo of the issue here.
[https://stackblitz.com/edit/fxflexfill-issue](https://stackblitz.com/edit/fxflexfill-issue)
*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release:

**Comment by CaerusKaru** [comment]
Demo leads to a 404

**Comment by wizzardz** [comment]
@CaerusKaru fixed the link issue

**Comment by CaerusKaru** [comment]
The problem is that on StackBlitz, the `div` containing the actual Angular app is not set to `height: 100%`. If you add ```#blitz-app {
  height: 100%;
}``` to the `styles.css` file, you will see correct behavior. If you examine the CSS, you'll see that all of the elements are applying the correct inline CSS, but it's worthless because the containing element has a restricted height within the body.
