### ISSUE TITLE
Overlapping breakpoints with ngClass doesn't apply on initial load, only works correctly on window resize

### ISSUE THREAD

**Issue by adamdport** [angular/flex-layout#648]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
if I have overlapping breakpoints on a div, the nearest breakpoint is applied on initial load.

#### What is the current behavior?
The wrong breakpoint is applied on initial load, but is correct after resizing the window to another breakpoint and returning

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-i45rb6

#### What is the use-case or motivation for changing an existing behavior?
The class that applies on load should be the correct class

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "5.2.7"
"@angular/flex-layout": "5.0.0-beta.13"
"@angular/material": "5.2.3"
Chrome 64

**Comment by CaerusKaru** [comment]
Ok so there's good news and bad news. The good news is that you're definitely not crazy, and this is inconsistent behavior.

The bad news is that this is actually working exactly as its designed to work. Here's the logic: when there are competing breakpoints that are activated, the one with the widest range wins (this is documented on the Wiki, and means that lt-md > lt-sm, therefore blue). So on startup, all of the breakpoints become active at the same time and compete, and lt-md wins. BUT, when the window is resized, lt-sm is first deactivated, and then re-activated, meaning that the reactivation event triggered the green layout to appear.

Is any of this _correct_? Honestly, I have a hard time knowing. I am _very_ open to discussion on this, because it is a glaring inconsistency with how we treat breakpoints.

**Comment by CaerusKaru** [comment]
We're going to target this for the next beta round, which should land in a couple weeks.
