### ISSUE TITLE
Custom BreakPoints documentation

### ISSUE THREAD

**Issue by nrone** [angular/flex-layout#744]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Working documentation example

#### What is the current behavior?
Non-working example

#### What are the steps to reproduce?
Last example in the documentation, https://github.com/angular/flex-layout/wiki/Breakpoints are extending upon "ShowHideDirective"

```typescript
export class CustomShowHideDirective extends ShowHideDirective {
  constructor(monitor: MediaMonitor, elRef: ElementRef, renderer: Renderer2) {
    super(monitor, elRef, renderer);
  }

  @Input('fxHide.xs.print')
  set hideXs(val) {
    this._cacheInput("showXsPrint", negativeOf(val));
  }
}
```

The issue is "ShowHideDirective" takes 6 required arguments, not 3.

```
[ts] Expected 6 arguments, but got 3.
constructor ShowHideDirective(monitor: MediaMonitor, layout: LayoutDirective, elRef: ElementRef<any>, styleUtils: StyleUtils, platformId: Object, serverModuleLoaded: boolean): ShowHideDirective
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/cdk": "6.0.0",
"@angular/flex-layout": "^6.0.0-beta.15",

**Comment by wilhelmhb** [comment]
This problem has already been reported. The issue has been closed even though the documentation hasn't been updated...
I'm now used to check for the code directly instead of looking into the doc.
Direct links to the files:
- ShowHide: src/lib/extended/show-hide/show-hide.ts
- Layout: src/lib/extended/show-hide/show-hide.ts
- Class: src/lib/extended/class/class.ts
- Style: src/lib/extended/style/style.ts

Copy-pasting the constructor's signature usually works for me:
```typescript
constructor([pasted]) {
    super([pasted args]);
}
```

**Comment by CaerusKaru** [comment]
I've just updated the Wiki page. There were a couple reasons this slipped through, and it was mainly because we're working on completely revamping the docs site, and this got missed in the process.

Please note for the future that we accept PRs for our Wiki documentation, which is located in docs/documentation
