### ISSUE TITLE
Flex layout/element vertical centering doesn't work

### ISSUE THREAD

**Issue by aivaras-b** [angular/flex-layout#762]
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?

Elements within `fxLayoutAlign="center"` / `fxFlexAlign="center"` to vertically centered.
#### What is the current behavior?

Elements remain at top and only centered horizontally.
#### What are the steps to reproduce?
Providing a StackBlitz (or similar) is the *best* way to get the team to see your issue.

*  [StackBlitz starter](https://goo.gl/y38GUZ) using latest `npm` nightly release: 

https://stackblitz.com/edit/angular-flex-layout-seed-ucjgcl?file=app%2Ftest.component.ts
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Seems like it can be reproduced on flex-layout 5.0.0-beta.14 and also on 6.0.0-beta.15
#### Is there anything else we should know?

**Comment by CaerusKaru** [comment]
Your problem is that you have a div you want to align within another div. Flexbox is not recursive. It has a very specific child/parent relationship. Just add a `fxLayout` to the containing `div` about `second-content` and it should fix your issue (along with adding `fxFlexAlign="center"` to the second content `div`).

**Comment by aivaras-b** [comment]
I see, got carried away trying to apply same logic as angular material 1. Thanks for info!
