### ISSUE TITLE
Custom Breakpoints is bad

### ISSUE THREAD

**Issue by AmirFawzy** [angular/flex-layout#802]
# Proposal

#### What is the summary of the proposal?
i know is not a totally new proposal but the configuration exist right now about how you can overriding the default breakpoints or how to provide the new one is totally confusing and not explain with examples how to implement such new custom breakpoints and the documentation also is not updated there's some features is exist in the doc but is removed in the existing version 6.0.0-beta.16 specially in part talking about how to make a custom breakpoints.
the way of how to implement new breakpoints is not clear, explained and not easy.

#### Is there anything else we should know?
1- please take a look on doc it's old and not updated.
2- trying to simplify the way of creating custom breakpoints it's the most important thing in any layout.

**Comment by CaerusKaru** [comment]
This reads more as a complaint than a proposal. This project is open-source, and benefits greatly from the input and direction of its users. That being said, if you can provide some _actionable_ ideas or proposals, we would be more than happy to investigate.

As it is, I have no idea which docs you're referring to, and while custom breakpoints are important, we believe in our current implementation unless there is a superior option provided to us.

Unless this issue is updated with the above links and actual proposal, it will be closed.
