### ISSUE TITLE
Fxhide does not hide content on initial load after the newest .17 beta under certain conditions

### ISSUE THREAD

**Issue by Nikki1993** [angular/flex-layout#812]
# Bug Report
Fxhide does not hide content on initial load. Only after resizing the window from desktop size to mobile size and back is the content properly hidden.
#### What is the expected behavior?
fxHide hides the content

#### What is the current behavior?
fxHide does not hide the content until it's resized to specific media sizes to trigger

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-flex-layout-seed-163nfp
Here is the sample code that's very similar to the project I am using it on. Resize the window and notice how only after making it smaller to trigger the change do button and span actually hide when resizing the window back.

#### What is the use-case or motivation for changing an existing behavior?
Worked on the last beta, does not work anymore. Reverting back to .16 beta resolves the issue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
    "@angular/material": "^6.4.1",
    "typescript": "~2.9.2"
    "@angular/core": "^6.1.0",

I can reproduce this in Google Chrome, Firefox Developer Edition, Edge.

**Comment by CaerusKaru** [comment]
I'm going to consolidate this into #848. The reason this is happening is because we're adding `display: flex` indiscriminately in certain cases. A temporary workaround may be to use `FlexLayoutModule.withConfig({addFlexToParent: false})`, although that may not fix every issue. This is unfortunately more complicated that it may seem, which I'll elaborate on in #848
